var CACHE = "ayalungoo-school-12";
var ASSETS = [
  "/",
  "/index.html",
  "/manifest.json",
  "/icon.svg",
  "/icon-192.png",
  "/icon-512.png",
  "/melody.html",
  "/amita-show.html",
  "/swimming/",
  "/swimming/index.html",
  "/swimming/lesson.html",
  "/swimming/lessons.js",
  "/swimming/school.css",
  "/swimming/amita.css",
  "/swimming/amita.js",
  "/swimming/scenes.js",
  "/swimming/rig.js",
  "/swimming/keyframes.js",
  "/swimming/frames/backstroke-0.jpg",
  "/swimming/frames/backstroke-1.jpg",
  "/swimming/frames/backstroke-2.jpg",
  "/swimming/frames/backstroke-3.jpg",
  "/swimming/frames/bottom-turn-0.jpg",
  "/swimming/frames/bottom-turn-1.jpg",
  "/swimming/frames/bottom-turn-2.jpg",
  "/swimming/frames/bottom-turn-3.jpg",
  "/swimming/frames/breaststroke-0.jpg",
  "/swimming/frames/breaststroke-1.jpg",
  "/swimming/frames/breaststroke-2.jpg",
  "/swimming/frames/breaststroke-3.jpg",
  "/swimming/frames/breath-0.jpg",
  "/swimming/frames/breath-1.jpg",
  "/swimming/frames/breath-2.jpg",
  "/swimming/frames/breath-3.jpg",
  "/swimming/frames/butterfly-0.jpg",
  "/swimming/frames/butterfly-1.jpg",
  "/swimming/frames/butterfly-2.jpg",
  "/swimming/frames/butterfly-3.jpg",
  "/swimming/frames/catch-wave-0.jpg",
  "/swimming/frames/catch-wave-1.jpg",
  "/swimming/frames/catch-wave-2.jpg",
  "/swimming/frames/catch-wave-3.jpg",
  "/swimming/frames/climb-out-0.jpg",
  "/swimming/frames/climb-out-1.jpg",
  "/swimming/frames/climb-out-2.jpg",
  "/swimming/frames/climb-out-3.jpg",
  "/swimming/frames/dolphin-0.jpg",
  "/swimming/frames/dolphin-1.jpg",
  "/swimming/frames/dolphin-2.jpg",
  "/swimming/frames/dolphin-3.jpg",
  "/swimming/frames/duck-dive-0.jpg",
  "/swimming/frames/duck-dive-1.jpg",
  "/swimming/frames/duck-dive-2.jpg",
  "/swimming/frames/duck-dive-3.jpg",
  "/swimming/frames/elementary-back-0.jpg",
  "/swimming/frames/elementary-back-1.jpg",
  "/swimming/frames/elementary-back-2.jpg",
  "/swimming/frames/elementary-back-3.jpg",
  "/swimming/frames/float-back-0.jpg",
  "/swimming/frames/float-back-1.jpg",
  "/swimming/frames/float-back-2.jpg",
  "/swimming/frames/float-back-3.jpg",
  "/swimming/frames/float-tummy-0.jpg",
  "/swimming/frames/float-tummy-1.jpg",
  "/swimming/frames/float-tummy-2.jpg",
  "/swimming/frames/float-tummy-3.jpg",
  "/swimming/frames/flutter-0.jpg",
  "/swimming/frames/flutter-1.jpg",
  "/swimming/frames/flutter-2.jpg",
  "/swimming/frames/flutter-3.jpg",
  "/swimming/frames/freestyle-0.jpg",
  "/swimming/frames/freestyle-1.jpg",
  "/swimming/frames/freestyle-2.jpg",
  "/swimming/frames/freestyle-3.jpg",
  "/swimming/frames/frog-0.jpg",
  "/swimming/frames/frog-1.jpg",
  "/swimming/frames/frog-2.jpg",
  "/swimming/frames/frog-3.jpg",
  "/swimming/frames/glide-0.jpg",
  "/swimming/frames/glide-1.jpg",
  "/swimming/frames/glide-2.jpg",
  "/swimming/frames/glide-3.jpg",
  "/swimming/frames/help-float-0.jpg",
  "/swimming/frames/help-float-1.jpg",
  "/swimming/frames/help-float-2.jpg",
  "/swimming/frames/help-float-3.jpg",
  "/swimming/frames/huddle-0.jpg",
  "/swimming/frames/huddle-1.jpg",
  "/swimming/frames/huddle-2.jpg",
  "/swimming/frames/huddle-3.jpg",
  "/swimming/frames/knees-balance-0.jpg",
  "/swimming/frames/knees-balance-1.jpg",
  "/swimming/frames/knees-balance-2.jpg",
  "/swimming/frames/knees-balance-3.jpg",
  "/swimming/frames/lake-swim-0.jpg",
  "/swimming/frames/lake-swim-1.jpg",
  "/swimming/frames/lake-swim-2.jpg",
  "/swimming/frames/lake-swim-3.jpg",
  "/swimming/frames/ocean-entry-0.jpg",
  "/swimming/frames/ocean-entry-1.jpg",
  "/swimming/frames/ocean-entry-2.jpg",
  "/swimming/frames/ocean-entry-3.jpg",
  "/swimming/frames/ocean-exit-0.jpg",
  "/swimming/frames/ocean-exit-1.jpg",
  "/swimming/frames/ocean-exit-2.jpg",
  "/swimming/frames/ocean-exit-3.jpg",
  "/swimming/frames/ocean-trip-0.jpg",
  "/swimming/frames/ocean-trip-1.jpg",
  "/swimming/frames/ocean-trip-2.jpg",
  "/swimming/frames/ocean-trip-3.jpg",
  "/swimming/frames/paddle-0.jpg",
  "/swimming/frames/paddle-1.jpg",
  "/swimming/frames/paddle-2.jpg",
  "/swimming/frames/paddle-3.jpg",
  "/swimming/frames/pop-up-0.jpg",
  "/swimming/frames/pop-up-1.jpg",
  "/swimming/frames/pop-up-2.jpg",
  "/swimming/frames/pop-up-3.jpg",
  "/swimming/frames/reach-rescue-0.jpg",
  "/swimming/frames/reach-rescue-1.jpg",
  "/swimming/frames/reach-rescue-2.jpg",
  "/swimming/frames/reach-rescue-3.jpg",
  "/swimming/frames/rip-0.jpg",
  "/swimming/frames/rip-1.jpg",
  "/swimming/frames/rip-2.jpg",
  "/swimming/frames/rip-3.jpg",
  "/swimming/frames/river-cross-0.jpg",
  "/swimming/frames/river-cross-1.jpg",
  "/swimming/frames/river-cross-2.jpg",
  "/swimming/frames/river-cross-3.jpg",
  "/swimming/frames/river-entry-0.jpg",
  "/swimming/frames/river-entry-1.jpg",
  "/swimming/frames/river-entry-2.jpg",
  "/swimming/frames/river-entry-3.jpg",
  "/swimming/frames/river-exit-0.jpg",
  "/swimming/frames/river-exit-1.jpg",
  "/swimming/frames/river-exit-2.jpg",
  "/swimming/frames/river-exit-3.jpg",
  "/swimming/frames/roll-breathe-0.jpg",
  "/swimming/frames/roll-breathe-1.jpg",
  "/swimming/frames/roll-breathe-2.jpg",
  "/swimming/frames/roll-breathe-3.jpg",
  "/swimming/frames/scull-0.jpg",
  "/swimming/frames/scull-1.jpg",
  "/swimming/frames/scull-2.jpg",
  "/swimming/frames/scull-3.jpg",
  "/swimming/frames/shallow-dive-0.jpg",
  "/swimming/frames/shallow-dive-1.jpg",
  "/swimming/frames/shallow-dive-2.jpg",
  "/swimming/frames/shallow-dive-3.jpg",
  "/swimming/frames/sidestroke-0.jpg",
  "/swimming/frames/sidestroke-1.jpg",
  "/swimming/frames/sidestroke-2.jpg",
  "/swimming/frames/sidestroke-3.jpg",
  "/swimming/frames/sighting-0.jpg",
  "/swimming/frames/sighting-1.jpg",
  "/swimming/frames/sighting-2.jpg",
  "/swimming/frames/sighting-3.jpg",
  "/swimming/frames/sit-entry-0.jpg",
  "/swimming/frames/sit-entry-1.jpg",
  "/swimming/frames/sit-entry-2.jpg",
  "/swimming/frames/sit-entry-3.jpg",
  "/swimming/frames/soft-body-0.jpg",
  "/swimming/frames/soft-body-1.jpg",
  "/swimming/frames/soft-body-2.jpg",
  "/swimming/frames/soft-body-3.jpg",
  "/swimming/frames/stand-entry-0.jpg",
  "/swimming/frames/stand-entry-1.jpg",
  "/swimming/frames/stand-entry-2.jpg",
  "/swimming/frames/stand-entry-3.jpg",
  "/swimming/frames/streamline-0.jpg",
  "/swimming/frames/streamline-1.jpg",
  "/swimming/frames/streamline-2.jpg",
  "/swimming/frames/streamline-3.jpg",
  "/swimming/frames/survival-back-0.jpg",
  "/swimming/frames/survival-back-1.jpg",
  "/swimming/frames/survival-back-2.jpg",
  "/swimming/frames/survival-back-3.jpg",
  "/swimming/frames/takeoff-0.jpg",
  "/swimming/frames/takeoff-1.jpg",
  "/swimming/frames/takeoff-2.jpg",
  "/swimming/frames/takeoff-3.jpg",
  "/swimming/frames/tread-0.jpg",
  "/swimming/frames/tread-1.jpg",
  "/swimming/frames/tread-2.jpg",
  "/swimming/frames/tread-3.jpg",
  "/swimming/frames/trim-0.jpg",
  "/swimming/frames/trim-1.jpg",
  "/swimming/frames/trim-2.jpg",
  "/swimming/frames/trim-3.jpg",
  "/swimming/frames/tummy-balance-0.jpg",
  "/swimming/frames/tummy-balance-1.jpg",
  "/swimming/frames/tummy-balance-2.jpg",
  "/swimming/frames/tummy-balance-3.jpg",
  "/swimming/frames/turtle-roll-0.jpg",
  "/swimming/frames/turtle-roll-1.jpg",
  "/swimming/frames/turtle-roll-2.jpg",
  "/swimming/frames/turtle-roll-3.jpg",
  "/swimming/frames/wave-breath-0.jpg",
  "/swimming/frames/wave-breath-1.jpg",
  "/swimming/frames/wave-breath-2.jpg",
  "/swimming/frames/wave-breath-3.jpg",
  "/swimming/frames/whitewater-0.jpg",
  "/swimming/frames/whitewater-1.jpg",
  "/swimming/frames/whitewater-2.jpg",
  "/swimming/frames/whitewater-3.jpg",
  "/swimming/frames/wipeout-0.jpg",
  "/swimming/frames/wipeout-1.jpg",
  "/swimming/frames/wipeout-2.jpg",
  "/swimming/frames/wipeout-3.jpg",
  "/swimming/amita-locked.jpg",
  "/swimming/parts/body.png",
  "/swimming/parts/arm-l.png",
  "/swimming/parts/arm-r.png",
  "/swimming/parts/thigh-l.png",
  "/swimming/parts/thigh-r.png",
  "/swimming/parts/calf-l.png",
  "/swimming/parts/calf-r.png",
  "/swimming/hero-banner.jpg",
  "/swimming/app.js"
];

self.addEventListener("install", function (event) {
  event.waitUntil(caches.open(CACHE).then(function (cache) {
    return cache.addAll(ASSETS);
  }));
  self.skipWaiting();
});

self.addEventListener("activate", function (event) {
  event.waitUntil(caches.keys().then(function (keys) {
    return Promise.all(keys.filter(function (key) {
      return key !== CACHE;
    }).map(function (key) {
      return caches.delete(key);
    }));
  }).then(function () {
    return self.clients.claim();
  }));
});

self.addEventListener("fetch", function (event) {
  var req = event.request;
  if (req.method !== "GET") return;
  var url = new URL(req.url);
  if (url.origin !== self.location.origin) return;
  event.respondWith((async function () {
    try {
      var fresh = await fetch(req);
      var cache = await caches.open(CACHE);
      cache.put(req, fresh.clone());
      return fresh;
    } catch (err) {
      var cached = await caches.match(req);
      if (cached) return cached;
      if (req.mode === "navigate") return caches.match("/index.html");
      throw err;
    }
  })());
});
